### ISSUE TITLE
Automate the process of generating releases using GitHub action

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#109]
Automate the process of generating releases and changelog using a GitHub action by using conventional-commit workflow.

The implementation for the above action using `yaml` may look like this:

``` yaml
on:
  workflow_dispatch:
    branches: main

jobs:
  release:
    name: Perform release
        - uses: actions/checkout@v2
            with:
              fetch-depth: 0

        - name: Cocogitto release
          id: release
          uses: oknozor/cocogitto-action@v2
          with:
            release: true
              git-user: 'Cog Bot'
              git-user-email: 'mycoolproject@org.org'

        - name: Generate Changelog
          run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

        - name: Upload github release
          uses: softprops/action-gh-release@v1
          with:
            body_path: GITHUB_CHANGELOG.md
            tag_name: ${{ steps.release.outputs.version }}

        runs-on: ubuntu-latest

        steps:
            # check out the repository with all releases
            - uses: actions/checkout@v3
            with:
                fetch-depth: 0

            # Create a temporary, uniquely named branch to push release info to
            - name: create temporary branch
            run: git branch "release-from-${{ github.sha }}" "${{ github.sha }}"

            # switch to the temporary branch
            - name: switch to new branch
            run: git checkout release-from-${{ github.sha }}

        steps:
            - name: Checkout
            uses: actions/checkout@v2.4.2

            - name: Cargo Semver Update
            id: update
            uses: lemonxah/cargo_semver_update@v1.0.3

            - name: Commit file
            uses: swinton/commit@v2.x
            env:
                GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
            with:
                files: |
                    Cargo.toml
                commit-message: Updating Cargo semver version to ${{ steps.update.outputs.new_version }} # commit message including the new version

            # create PR using GitHub CLI
            - name: create PR with release info
            id: create-pr
            run: gh pr create --base main --head release-from-${{ github.sha }} --title 'Merge new release into main' --body 'Created by Github action'
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # merge PR using GitHub CLI
            - name: merge PR with release info
            id: merge-pr
            run: gh pr merge --admin --merge --subject 'Merge release info' --delete-branch
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
> **Note**
> The above **yaml** code has been adapted from these github actions:
> - [https://docs.cocogitto.io/ci_cd/#github-release-changelog](https://docs.cocogitto.io/ci_cd/#github-release-changelog)
> - [https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/release.yml](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/release.yml)
> - [https://github.com/lemonxah/cargo_semver_update](https://github.com/lemonxah/cargo_semver_update)
