### ISSUE TITLE
Make improvements to `colorschemes` to make it look right 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#124]
Currently, there are 12 colorschemes available for the website, located under the `public/static/colorschemes/` folder in the project. These colorschemes allow the user to change the color of the theme being used on the website. They all are written in `CSS` and have 9 variables (as shown below with an example colorscheme) in each colorscheme file to play with. At present all colorschemes except the five colorschemes `catppuccin-mocha`, `dracula`, `tokyo-night`, `one-dark` and `dark-chocolate` requires a fix.

``` css
:root {
  --bg: #44475a;
  --fg: #8be9fd;
  --1: #ff5555;
  --2: #50fa7b;
  --3: #ffb86c;
  --4: #bd93f9;
  --5: #ff79c6;
  --6: #94a3a5;
  --7: #ffffff;
}
```

For reference, you can take a look at the color palettes located [here](https://terminal.sexy/) and [here](https://gogh-co.github.io/Gogh/). 

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
> are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
> are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
> contributing :slightly_smiling_face: .
