### ISSUE TITLE
✨ Docker compose for development

### ISSUE THREAD

**Issue by 0xle0ne** [neon-mmd/websurfx#320]
### Description

Could be nice and smoother if we can start the project in development using `docker compose up`.
It need to have a specific `Dockerfile` with `rust` and `cargo watch` so everytime we update the code the build rerun inside the development container.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Thanks ❤️ for taking the time opening this. We really appreciate it 👍 as it helps improve our project. 

I didn't really get your point with the development `docker compose` file like we do already provide a docker compose to ease the process of deployment so could you please explain like what you mean by development docker compose file ? And what it will look like?

Also, as a reference I would suggest going through the `installation docs` [here](https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#docker-deployment). so that we can have a better discussion on this topic 🙂 .

**Comment by 0xle0ne** [comment]
The provided docker compose is for production.
A docker compose for development look like this:

```yaml
version: 3.9
services:
  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    hostname: surfx-redis
  websurx:
    container_name: websurx-dev
    image: websurfx:dev
    working_dir: /project
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /project
    command:
      - watch
      - -x
      - run
```

This allow better reproductibility and will work no matter the contributor exploitation system, (windows, macos).
It's a suggestion if you think it's not necessarily then we can close the issue.
But i personally use development docker compose for all my project.
