### ISSUE TITLE
👷 Github actions to release docker image

### ISSUE THREAD

**Issue by 0xle0ne** [neon-mmd/websurfx#323]
### Description

A github actions can be considered to automatically build and publish docker image for production.
The idea is to trigger the workflow when we push on a specific branch for example: `release/{version}`

### Do you want to work on this issue?

Yes

**Comment by 0xle0ne** [comment]
Hey @neon-mmd i wont be able to work on this without proper permission.

This is the error i get:
![image](https://github.com/neon-mmd/websurfx/assets/7750950/7a71fe0f-818f-4953-ba5e-e5469b1e32eb)

So i recommand you to give it a shot yourself !
This is what the release workflow should look like:

```yaml
name: Release stable image

on:
  push:
    branches:
      - "release/stable/**"
  pull_request:
    branches:
      - "release/stable/**"
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_image:
    strategy:
      fail-fast: false
      matrix:
        cache:
          - memory
          - redis
          - hybrid
          - no-cache

    name: Release ${{ matrix.cache }} image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Install buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      # Set buildx cache
      - name: Cache register
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-cache
      # Login to ghcr.io
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: neon-mmd
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract branch info
      - name: Set info
        run: |
          echo "VERSION=$(echo ${GITHUB_REF} | awk -F/ '{print $6}')" >> $GITHUB_ENV
      # Print info for debug
      - name: Print Info
        run: |
          echo $VERSION
      # Create buildx multiarch
      - name: Create buildx multiarch
        run: docker buildx create --use --name=buildx-multi-arch --driver=docker-container --driver-opt=network=host
      # Publish image
      - name: Publish image
        run: docker buildx build --builder=buildx-multi-arch --platform=linux/amd64,linux/arm64 --build-arg CACHE=${{ matrix.cache }} --push -t ghcr.io/neon-mmd/websurfx:$VERSION-${{ matrix.cache }} -t ghcr.io/neon-mmd/websurfx:latest -f Dockerfile .
      - name: Publish latest
        if: ${{ matrix.cache }} == 'hybrid'
        run: docker buildx build --builder=buildx-multi-arch --platform=linux/amd64,linux/arm64 --build-arg CACHE=${{ matrix.cache }} --push -t ghcr.io/neon-mmd/websurfx:latest -f Dockerfile .
      # Upload it to release
      - name: Test if release already exists
        id: release-exists
        continue-on-error: true
        run: gh release view $BINARY_NAME-$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new draft release
        if: steps.release-exists.outcome == 'failure' && steps.release-exists.conclusion == 'success'
        run: gh release create -t $VERSION -d $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Using this workflow you should be able to automatise the release of the docker image for all cache types and both arm64 and x86_64 architecture.
