### ISSUE TITLE
Provide more famous colorschemes 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#77]
Provide more famous colorschemes like `Tokyonight` by adding them under the `public/static/colorschemes` folder located in the codebase (project folder). 

To add more colorschemes you will need to add the following code in the new colorscheme file:

``` css 
:root{
  --bg: <background color>;
  --fg: <foreground color (text color)>;
  --1: <color 1>;
  --2: <color 2>;
  --3: <color 3>;
  --4: <color 4>;
  --5: <color 5>;
  --6: <color 6>;
  --7: <color 7>;
}
```

Change the variable values with the colors you want to add in the above-provided code snippet.
